## Stub to invoke targets of ../Makefile

.PHONY : joos all joos.native joos.byte joos.top joos.debug joos.profile

joos:
	cd ..; $(MAKE) joos
all:
	cd ..; $(MAKE) all
joos.native:
	cd ..; $(MAKE) joos.native
joos.byte:
	cd ..; $(MAKE) joos.byte
joos.top:
	cd ..; $(MAKE) joos.top
joos.debug:
	cd ..; $(MAKE) joos.debug
joos.profile:
	cd ..; $(MAKE) joos.profile
clean:
	cd ..; $(MAKE) clean
htdoc:
	cd ..; $(MAKE) htdoc
